# -*- coding: utf-8 -*-
"""K-Means Clustering from Scratch

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lbJIyNiXiaLpxxDTuF363Nn9JYSHAHEh
"""

import numpy as np
import matpltlib.yplot as plt
from sklearm. datasets import make_blobs


#Create dataset
X, y = make_blobs(n_samples=300,centers=4,random_state=42)

class KMeans:
  def__init__(self,K=3,max_iters=100):
    self.k = k
    self.max_iter = max_iter
    self.centroids = None
    self.labels = None

  def fit(self,X):
      n_samples,n_features = X.shape

      #step 1. Intitialize centroids
      random_indices = np.random.choice(n_samples,self.k,replace=False)
      self.centroids = X[random_indices]

      for _ in range(self.max_iters):
        #step 2. Compute distances
        distances = np.zeros((n_samples,self.k))
        for i in range(self.k):
          distance[:,i]=np.sqrt(np.sum((X-self.centroids[i])**2,axis=1))

          #setp 3. Assign clusters
          self.labels = np.argmin(distances,axis=1)

          #step 4. Update centroids
          new_new_centdroids = np.zeros((self.k,n_features))
          for i in range(self.k):
            cluster_points = X[self.labels==i]
            if len(cluster_points) > 0:
              new_centroids[i] = np.mean(cluster_points,axis=0)
            else:
              new_centroids[i] = self.centroids[i]
          #step 5. Cheak conveergence
          if np.allclose(self.centroids,new_centroids):
            break
          self.centroids = new_centroids
          def calculate_wcss(self,X):
            wcss = 0
            for i in range(self.k):
              cluster_points = X[self.labels==i]
              wcss += np.sum((cluster_points-self.centroids[i])**2)
            return wcss

#------------------------------
#Elbow Method
#------------------------------
wcss = []
for k in range(1,11):
  models =KMeans(k=k)
  models.fit(X)
  wcss = model.calculate_wcss(X)
  wcss_values.append(wcss)

plt.figure()
plt.plot(rabge(1,11),wcss_values)
plt.xlabel("Number of Clusters (k)")
plt.ylabel("WCSS")
plt.title("Elbow Methot")
plt.show()